### ISSUE TITLE
ValueError: too many values to unpack (expected 2) on schema reload on 1.7.6

### ISSUE THREAD

**Issue by bofm** [tarantool/tarantool-python#100]
Python 3.6.4
tarantool==0.6.1

### Test case:
```python
import subprocess
import tarantool

try:
    subprocess.check_call('docker run --rm -d -p 3301:3301 --name tt_test progaudi/tarantool:1.7.6 && sleep 2', shell=True)
    t = tarantool.Connection('localhost', 3301)
    try:
        t.eval('''box.once(
            "schema:v1.0",
            function()
                local s = box.schema.space.create("s1")
                s:format(
                    {
                        {name = "f1", type = "string", is_nullable = false},
                    }
                )
                s:create_index("primary", {type = "hash", parts = {{"f1", "string", is_nullable = false}}})
            end
        )''')
        t.space('s1').select()
    finally:
        t.close()
finally:
    subprocess.check_call('docker rm -fv tt_test', shell=True)
```

### Error:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tarantool/connection.py", line 261, in _send_request_wo_reconnect
    response = Response(self, self._read_response())
  File "/usr/lib/python3.6/site-packages/tarantool/response.py", line 85, in __init__
    self._schema_version)
tarantool.error.SchemaReloadException: Wrong schema version, current: 69, in request: 72

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/tarantool_test.py", line 23, in <module>
    t.space('s1').select()
  File "/usr/lib/python3.6/site-packages/tarantool/connection.py", line 774, in space
    return Space(self, space_name)
  File "/usr/lib/python3.6/site-packages/tarantool/space.py", line 27, in __init__
    self.space_no = self.connection.schema.get_space(space_name).sid
  File "/usr/lib/python3.6/site-packages/tarantool/schema.py", line 83, in get_space
    return self.fetch_space(space)
  File "/usr/lib/python3.6/site-packages/tarantool/schema.py", line 86, in fetch_space
    space_row = self.fetch_space_from(space)
  File "/usr/lib/python3.6/site-packages/tarantool/schema.py", line 117, in fetch_space_from
    index=_index)
  File "/usr/lib/python3.6/site-packages/tarantool/connection.py", line 759, in select
    response = self._send_request(request)
  File "/usr/lib/python3.6/site-packages/tarantool/connection.py", line 341, in _send_request
    return self._send_request_wo_reconnect(request)
  File "/usr/lib/python3.6/site-packages/tarantool/connection.py", line 264, in _send_request_wo_reconnect
    self.update_schema(e.schema_version)
  File "/usr/lib/python3.6/site-packages/tarantool/connection.py", line 349, in update_schema
    self.flush_schema()
  File "/usr/lib/python3.6/site-packages/tarantool/connection.py", line 353, in flush_schema
    self.load_schema()
  File "/usr/lib/python3.6/site-packages/tarantool/connection.py", line 345, in load_schema
    self.schema.fetch_index_all()
  File "/usr/lib/python3.6/site-packages/tarantool/schema.py", line 166, in fetch_index_all
    SchemaIndex(row, self.schema[row[0]])
  File "/usr/lib/python3.6/site-packages/tarantool/schema.py", line 29, in __init__
    for k, v in index_row[5]:
ValueError: too many values to unpack (expected 2)
```

**Comment by bofm** [comment]
duplicates #95

**Comment by Totktonada** [comment]
Closed as duplicate.
