### ISSUE TITLE
AttributeError: 'module' object has no attribute 'NUM'

### ISSUE THREAD

**Issue by ToPP13** [tarantool/tarantool-python#149]
pip install tarantool-python\>0.4

python 2.7.12
>>> tarantool.__version__
'0.6.6'

>>> tarantool.__dict__.keys()
['utils', '__path__', 'connect', 'ENCODING_DEFAULT', 'Schema', 'const', '__all__', 'space', 'MeshConnection', '__package__', 'RECONNECT_MAX_ATTEMPTS', '__doc__', 'schema', '__builtins__', '__file__', 'NetworkError', 'Connection', 'Error', '__name__', 'RECONNECT_DELAY', 'response', 'NetworkWarning', '__version__', 'SOCKET_TIMEOUT', 'request', 'connectmesh', 'mesh_connection', 'connection', 'error', 'SchemaError', 'DatabaseError']

>>> import tarantool
>>> tarantool.STR
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'STR'
>>> 

>>> import tarantool
>>> tarantool.NUM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'NUM'
>>>

**Comment by Totktonada** [comment]
Sorry for the long delay! As I see, those contants were removed more than six years ago in 0f9d99ecb770586ca011800a6e3921c3353c7459:

```diff
-# Tarantool data types
-RAW = 0
-NUM = 1
-NUM64 = 2
-STR = 3
```

I looked briefly at the old code and I guess that those constants were used to define a database schema on a client side, because ancient tarantool versions do not support defining a database schema on the server side. Now one can define a [space format](https://www.tarantool.io/en/doc/latest/reference/reference_lua/box_space/format/) on the server and the client will automatically fetch and interpret the schema to perform requests using space/index/field names.

Please, share more details about your usage scenario: maybe we can suggest how to better solve your problem.
