### ISSUE TITLE
Wrong exception if slab arena is full

### ISSUE THREAD

**Issue by bigbes** [tarantool/tarantool-python#40]
tarantool log:

```
2014-10-07 16:52:38.883 [16796] 102/iproto salloc.cc:378 E> ER_MEMORY_ISSUE: Failed to allocate 38 bytes in slab allocator for tuple
2014-10-07 16:52:42.351 [16796] 102/iproto salloc.cc:378 E> ER_MEMORY_ISSUE: Failed to allocate 38 bytes in slab allocator for tuple
```

traceback:

```
Traceback (most recent call last):
  File "load.py", line 23, in <module>
    r.save(validate=True)
  File "/home/sergeyorlov/work/tarantism/tarantism/model.py", line 74, in save
    self.insert(data)
  File "/home/sergeyorlov/work/tarantism/tarantism/model.py", line 81, in insert
    return self.get_space().insert(values)
  File "/home/sergeyorlov/.virtualenvs/tarantism/local/lib/python2.7/site-packages/tarantool/space.py", line 89, in insert
    BOX_RETURN_TUPLE if return_tuple else 0) | BOX_ADD)
  File "/home/sergeyorlov/.virtualenvs/tarantism/local/lib/python2.7/site-packages/tarantool/connection.py", line 278, in _insert
    return self._send_request(request, space_name)
  File "/home/sergeyorlov/.virtualenvs/tarantism/local/lib/python2.7/site-packages/tarantool/connection.py", line 227, in _send_request
    request, space_name, field_defs, default_type)
  File "/home/sergeyorlov/.virtualenvs/tarantism/local/lib/python2.7/site-packages/tarantool/connection.py", line 169, in _send_request_wo_reconnect
    self, header, body, space_name, field_defs, default_type)
  File "/home/sergeyorlov/.virtualenvs/tarantism/local/lib/python2.7/site-packages/tarantool/response.py", line 138, in __init__
    self._unpack_body(body)
  File "/home/sergeyorlov/.virtualenvs/tarantism/local/lib/python2.7/site-packages/tarantool/response.py", line 237, in _unpack_body
    "<%ds" % (tuple_size), buff, offset + 4)[0]
struct.error: unpack_from requires a buffer of at least 1948279913 bytes
```

must be `DatabaseError`

**Comment by bekbulatov** [comment]
2015-02-24 12:47:02.276 [757] 107/iproto salloc.cc:385 E> ER_MEMORY_ISSUE: Failed to allocate 1135665 bytes in slab allocator for tuple
	2015-02-24 12:47:03.029 [757] 107/iproto salloc.cc:385 E> ER_MEMORY_ISSUE: Failed to allocate 1178195 bytes in slab allocator for tuple

Error occurs after insert huge tuple (more than 1Mb text in tarantool queue). Tried to increase `slab_alloc_arena`, but doesn't help. Below is my configuration:

	---
	slab statistics:
	  classes:
	     - { item_size:    256, slabs:      1, items:          60, bytes_used:        15472, waste: 33.59%, bytes_free:      4178832 }
	     - { item_size: 1048576, slabs:      4, items:           6, bytes_used:      6291904, waste: 22.84%, bytes_free:     10485312 }
	  items_used: 0.15%
	  arena_used: 0.49%
	  waste: 27.70%
	  bytes_waste:      1746878
	...



	---
	configuration:
	  username: "tarantool"
	  local_hot_standby: "false"
	  bind_ipaddr: "INADDR_ANY"
	  coredump: "false"
	  admin_port: "33015"
	  replication_port: "0"
	  log_level: "5"
	  slab_alloc_arena: "4"
	  slab_alloc_minimal: "64"
	  slab_alloc_factor: "2"
	  work_dir: "/var/tarantool_box1.1"
	  snap_dir: "."
	  wal_dir: "."
	  script_dir: "."
	  pid_file: "box.pid"
	  logger: "cat - >> logs/tarantool.log"
	  logger_nonblock: "true"
	  io_collect_interval: "0"
	  backlog: "1024"
	  readahead: "1024000000"
	  snap_io_rate_limit: "0"
	  rows_per_wal: "50000"
	  wal_writer_inbox_size: "16384"
	  wal_mode: "fsync_delay"
	  wal_fsync_delay: "0"
	  wal_dir_rescan_delay: "0.1"
	  panic_on_snap_error: "true"
	  panic_on_wal_error: "false"
	  primary_port: "33013"
	  secondary_port: "33014"
	  too_long_threshold: "0.5"
	  custom_proc_title: (null)
	  memcached_port: "0"
	  memcached_space: "23"
	  memcached_expire: "false"
	  memcached_expire_per_loop: "1024"
	  memcached_expire_full_sweep: "3600"
	  replication_source: (null)
