### ISSUE TITLE
Dont work on windows

### ISSUE THREAD

**Issue by DmitryBezik** [tarantool/tarantool-python#42]
OS - Microsoft Windows Server 2012 Standard
Python - 2.7
```
>>import tarantool

Traceback (most recent call last):
  File "C:\LogsParser\parser.py", line 1, in <module>
    import tarantool
  File "C:\Python27\lib\site-packages\tarantool\__init__.py", line 6, in <module>
    from tarantool.connection import Connection
  File "C:\Python27\lib\site-packages\tarantool\connection.py", line 50, in <module>
    class Connection(object):
  File "C:\Python27\lib\site-packages\tarantool\connection.py", line 63, in Connection
    use_errno=True)(_libc.recv)
  File "C:\Python27\lib\ctypes\__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'recv' not found
```

**Comment by bigbes** [comment]
Sorry for long response, but it must me fixed now in 1.6 connector
