### ISSUE TITLE
Python3 doesn't work

### ISSUE THREAD

**Issue by zloidemon** [tarantool/tarantool-python#65]
Error:

```
    class Error(StandardError):
NameError: name 'StandardError' is not defined
```

I found already committed patch to sources with fixed issue. Would you like bump version and upload to pypi latest version?

**Comment by anatol** [comment]
see the same issue when running tests with python3

```
======================================================================
ERROR: tarantool (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tarantool
Traceback (most recent call last):
  File "/usr/lib/python3.5/unittest/loader.py", line 462, in _find_test_path
    package = self._get_module_from_name(name)
  File "/usr/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/build/python-tarantool/src/tarantool-0.5.1/tarantool/__init__.py", line 6, in <module>
    from tarantool.connection import Connection
  File "/build/python-tarantool/src/tarantool-0.5.1/tarantool/connection.py", line 22, in <module>
    from tarantool.response import Response
  File "/build/python-tarantool/src/tarantool-0.5.1/tarantool/response.py", line 15, in <module>
    from tarantool.error import DatabaseError, tnt_strerror
  File "/build/python-tarantool/src/tarantool-0.5.1/tarantool/error.py", line 28, in <module>
    class Error(StandardError):
NameError: name 'StandardError' is not defined
```

**Comment by rtsisyk** [comment]
```
tarantool/1.6/test-run/lib/tarantool-python/tarantool/connection.py in handshake(self)
    135     def handshake(self):
    136         greeting_buf = self._recv(IPROTO_GREETING_SIZE)
--> 137         greeting = greeting_decode(greeting_buf)
    138         if greeting.protocol != "Binary":
    139             raise NetworkError("Unsupported protocol: " + greeting.protocol)

tarantool/1.6/test-run/lib/tarantool-python/tarantool/utils.py in greeting_decode(greeting_buf)
     66         return result
     67     except Exception as e:
---> 68         raise ValueError("Invalid greeting: " + str(greeting_buf) + ":" + str(e))

ValueError: Invalid greeting: b'Tarantool 1.6.7 (Binary) 166ac153-3577-4bb7-a2f0-d954adc686dd  \nlZA2QMXEFgHq028L+sUbrgEWcELxQod8USbepycmk7E=                   \n':'str' does not support the buffer interface

````

**Comment by bigbes** [comment]
fixed in https://github.com/tarantool/tarantool-python/commit/b90eef6dbdf06463f8309fc835a201172ecae640

**Comment by bigbes** [comment]
Fixed
