### ISSUE TITLE
Error on .connect

### ISSUE THREAD

**Issue by vmarunov** [tarantool/tarantool-python#70]
OS - Microsoft Windows 7 x64
Python 2.7.11
tarantool-0.5.4-py2.7
```
>>> import tarantool
>>> tarantool.connect('48.12.22.123',3311)

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    tarantool.connect('48.12.22.123',3311)
  File "C:\Python27\lib\site-packages\tarantool\__init__.py", line 47, in connect
    encoding=encoding)
  File "C:\Python27\lib\site-packages\tarantool\connection.py", line 93, in __init__
    recv = self._sys_recv = libc.recv
  File "C:\Python27\lib\ctypes\__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "C:\Python27\lib\ctypes\__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'recv' not found
```

**Comment by vmarunov** [comment]
PR with the solution of this error:
https://github.com/tarantool/tarantool-python/pull/71

**Comment by bigbes** [comment]
PR is merged, sorry for long response. Thank you!
