### ISSUE TITLE
тарантул 1.8 + py

### ISSUE THREAD

**Issue by Chudinov** [tarantool/tarantool-python#87]
ранее была версия тарантула 1.7, с tarantool-python работало
вчера установил 1,8 (под убунту 16) скрипты на питоне больше не работают

Пример:
1. из консоли создал спейс, закинул в него 2-3 записи, сделал селект там же - тарантул вернул результат
2. в соседнем окне консоли запустил py в котором были только эти строки
```
#!/usr/bin/python
import tarantool
server = tarantool.connect("localhost", 3301)
demo = server.space('examples')
```

порт и спейс как в п.1, получил результат:

```
$ python connect.py
Traceback (most recent call last):
  File "connect.py", line 3, in <module>
    server = tarantool.connect("localhost", 3301)
  File "/usr/local/lib/python2.7/dist-packages/tarantool/__init__.py", line 50, in connect
    return_tuple=return_tuple)
  File "/usr/local/lib/python2.7/dist-packages/tarantool/connection.py", line 103, in __init__
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/tarantool/connection.py", line 136, in connect
    raise NetworkError(e)
tarantool.error.NetworkError: (111, 'Connection `refused')`
```
при этом в первом окне консоли появилась ошибка

```
tarantool> {{box.space.examples:select{3}}}
---
- - - - [3, 'wwwrrr']
...

tarantool> 2017-05-19 10:41:01.964 [12760] iproto xrow.cc:59 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet he
2017-05-19 10:41:01.964 [12760] iproto xrow.cc:59 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet header
2017-05-19 10:41:01.964 [12760] iproto xrow.cc:59 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet header
2017-05-19 10:41:01.964 [12760] iproto xrow.cc:59 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet header
2017-05-19 10:41:01.964 [12760] iproto xrow.cc:59 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet header
2017-05-19 10:41:01.964 [12760] iproto xrow.cc:59 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet header
2017-05-19 10:41:01.964 [12760] iproto xrow.cc:59 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet header
2017-05-19 10:41:01.964 [12760] iproto xrow.cc:59 E> ER_INVALID_MSGPACK: Invalid MsgPack - packet header
```

переустановил tarantool-python, повторил, результат тот же

**Comment by bigbes** [comment]
Please, try the latest 0.5.5 version, that I've pushed to PyPI 2 days ago

**Comment by bigbes** [comment]
Feel free to reopen this ticket in case you still have problems with this select
