### ISSUE TITLE
'module' object has no attribute 'PY2'

### ISSUE THREAD

**Issue by rtsisyk** [tarantool/tarantool-python#88]
```
root@66b074ce3c2c:/1.7/test# ./test-run.py box/
Traceback (most recent call last):
  File "./test-run.py", line 61, in <module>
    import lib
  File "/1.7/test-run/lib/__init__.py", line 6, in <module>
    from lib.tarantool_server import TarantoolServer
  File "/1.7/test-run/lib/tarantool_server.py", line 29, in <module>
    from lib.box_connection import BoxConnection
  File "/1.7/test-run/lib/box_connection.py", line 35, in <module>
    check_libs()
  File "/1.7/test-run/lib/utils.py", line 28, in check_libs
    __import__(mod_name)
  File "/1.7/test-run/lib/tarantool-python/tarantool/__init__.py", line 6, in <module>
    from tarantool.connection import Connection
  File "/1.7/test-run/lib/tarantool-python/tarantool/connection.py", line 21, in <module>
    from tarantool.response import Response
  File "/1.7/test-run/lib/tarantool-python/tarantool/response.py", line 8, in <module>
    from tarantool.const import (
  File "/1.7/test-run/lib/tarantool-python/tarantool/const.py", line 79, in <module>
    if six.PY2:
AttributeError: 'module' object has no attribute 'PY2'
```

Ubuntu Precise 
Tarantool 1.7.4
Python 2.7.3
six.__version__ == '1.1.0'

**Comment by bigbes** [comment]
`six.version == '1.1.0'`

It's old.. six years old.
